# Generated by Django 5.1.1 on 2024-09-21 03:24

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contact_e_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone-Number'),
        ),
    ]
